# **Library Loading**
---
---

In [1]:
from functions.database_actions_functions import extract_readinga_to_current_date, insert_new_station_readings, serve_whole_data

import threading

import os
from dotenv import load_dotenv

# **Adding New Station Readings**
---
---

In [2]:
list_tables = ['station_details', 'station_sensors', 'weather_readings']
username_postgres = os.getenv('USER_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')
db_name = 'data_warehouse_weather'

headers = {
    'X-API-Key': os.getenv('API_OPENAQ') # initializing request header
}

list_stations = ['Brent']
list_ids = [225719]

inp=list_stations
id_inp=list_ids

In [3]:
id_station_detail, merged_weather_pm25, station_details = insert_new_station_readings(username_postgres, pw_postgres, db_name, headers, station_names=list_stations, station_ids=list_ids, folder_name='datasets_temp', remove_folder_at_end=True)

Existence of DB data_warehouse_weather: True

Start: 2023-01-01 00:00:00, end: 2026-07-29 23:00:00
Getting sensors in Brent
Saved station details to: c:\Users\user\works\DE_studies\openmeteo_ml\datasets_temp\station_sensors.csv


Processing Brent: sensor 16317960

Processing Brent: sensor 6955371

<Response [200]> -- processing page 1 (end date 2024-01-01 - Brent: sensor 16317960)
Processed 0 records
Finished processing all records - Brent: sensor 16317960
<Response [200]> -- processing page 1 (end date 2024-01-01 - Brent: sensor 6955371)
Processed 1000 records
<Response [200]> -- processing page 2 (end date 2024-01-01 - Brent: sensor 6955371)
Processed 2000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - Brent: sensor 6955371)
Processed 2507 records
Finished processing all records - Brent: sensor 6955371

<Response [200]> -- processing page 1 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 3507 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 4507 records
<Response [200]> -- processing page 3 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 5507 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 6507 records
<Response [200]> -- processing page 5 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 7507 records
<Response [200]> -- processing page 6 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 8507 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 9507 records
<Response [200]> -- processing page 8 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 10507 records
<Response [200]> -- processing page 9 (end date 2025-01-01 - Brent: sensor 6955371)
Processed 10961 records
Finished processing all records - Brent: sensor 6955371

<Response [200]> -- processing page 1 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 11961 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 12961 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 13961 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 14961 records
<Response [200]> -- processing page 5 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 15961 records
<Response [200]> -- processing page 6 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 16961 records
<Response [200]> -- processing page 7 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 17961 records
<Response [200]> -- processing page 8 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 18961 records
<Response [200]> -- processing page 9 (end date 2026-01-01 - Brent: sensor 6955371)
Processed 19635 records
Finished processing all records - Brent: sensor 6955371
<Response [200]> -- processing page 1 (end date 2026-07-29 - Brent: sensor 6955371)
Processed 20635 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - Brent: sensor 6955371)
Processed 21635 records
<Response [200]> -- processing page 3 (end date 2026-07-29 - Brent: sensor 6955371)
Processed 22635 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - Brent: sensor 6955371)
Processed 23635 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - Brent: sensor 6955371)
Processed 24332 records
Finished processing all records - Brent: sensor 6955371

Saved readings to: c:\Users\user\works\DE_studies\openmeteo_ml\datasets_temp\sensor_readings.csv
Getting sensors in Brent

Processing Brent - long -0.247793 & lat 51.537799, status code: 200
Finished on Brent
Condition before cleaning:
On merged dataset found 0 duplicated records, missing value details:
time                       0
temperature_2m             0
relative_humidity_2m       0
wind_speed_10m             0
surface_pressure           0
rain                       0
station_id_london          0
station_name               0
long                       0
lat                        0
location_id             7012
location_name           7012
sensor_id               7012
values_pm25             7160
timestamp_from          7012
timestamp_to            7012
dtype: int64
Stations with > 1 sensors sending values? False
Stations with 0 sensors sending values? False
Stations with inconsistent names? 0

Condition after cleaning:
On merged dataset found 0 duplicated records, missing value details:
time                       0
temperature_2m             0
relative_humidity_2m       0
wind_speed_10m             0
surface_pressure           0
rain                       0
station_id_london          0
station_name               0
long                       0
lat                        0
location_id                0
location_name              0
sensor_id                  0
values_pm25             7160
timestamp_from             0
weather_id                 0
dtype: int64
Stations with > 1 sensors sending values? False
Stations with 0 sensors sending values? False
Stations with inconsistent names? 0
Existence of DB data_warehouse_weather: True

Processing for station_details
Finished on station_details

Processing for station_sensors
Finished on station_sensors

Processing for weather_readings
Finished on weather_readings

Removed temporary folder at c:\Users\user\works\DE_studies\openmeteo_ml\datasets_temp

In [4]:
serve_whole_data(username_postgres, pw_postgres, db_name, limit=10000)

Existence of DB data_warehouse_weather: True

c:\Users\user\works\DE_studies\openmeteo_ml\functions\database_actions_functions.py:164: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  table_result = pd.io.sql.read_sql_query(f'''

Saved cleaned, read-ML data to c:\Users\user\works\DE_studies\openmeteo_ml\datasets_aggr\weather_readings_mlready.csv

,weather_id,sensor_id,station_id,station_name,time_reading,temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,rain,pm25,longitude,latitude
0,W1561901_2023010100,1561901,270693,Waterloo Place,2023-01-01 00:00:00,12.1,89.0,34.1,999.1,0.3,5.1,-0.133068,51.507582
1,W1561901_2023010101,1561901,270693,Waterloo Place,2023-01-01 01:00:00,11.3,94.0,22.9,999.1,0.1,6.2,-0.133068,51.507582
2,W1561901_2023010102,1561901,270693,Waterloo Place,2023-01-01 02:00:00,11.9,85.0,31.1,999.9,0.4,6.6,-0.133068,51.507582
3,W1561901_2023010103,1561901,270693,Waterloo Place,2023-01-01 03:00:00,11.0,80.0,31.4,1000.9,0.0,7.9,-0.133068,51.507582
4,W1561901_2023010104,1561901,270693,Waterloo Place,2023-01-01 04:00:00,10.4,78.0,30.7,1001.9,0.0,8.3,-0.133068,51.507582
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219402,W6955371_2026072919,6955371,225719,Brent,2026-07-29 19:00:00,31.2,30.0,16.2,1006.0,0.0,NaN,-0.247793,51.537799
219403,W6955371_2026072920,6955371,225719,Brent,2026-07-29 20:00:00,29.9,34.0,16.1,1006.2,0.0,NaN,-0.247793,51.537799
219404,W6955371_2026072921,6955371,225719,Brent,2026-07-29 21:00:00,27.3,44.0,14.1,1007.0,0.0,NaN,-0.247793,51.537799
219405,W6955371_2026072922,6955371,225719,Brent,2026-07-29 22:00:00,25.6,49.0,11.5,1007.9,0.0,NaN,-0.247793,51.537799
219406,W6955371_2026072923,6955371,225719,Brent,2026-07-29 23:00:00,24.5,53.0,11.1,1008.1,0.0,NaN,-0.247793,51.537799

# **Extracting and Cleaning Up-to-Date Readings**
---
---

In [9]:
load_dotenv() # load environment variables
thread_local = threading.local() # Initializing thread local storage

list_tables = ['station_details', 'station_sensors', 'weather_readings']
username_postgres = os.getenv('USER_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')
db_name = 'data_warehouse_weather'

headers = {
    'X-API-Key': os.getenv('API_OPENAQ') # initializing request header
}

In [10]:
merged_readings=extract_readinga_to_current_date(username_postgres, pw_postgres, db_name, headers)

2026-08-30T11:00:00
Existence of DB data_warehouse_weather: True

Max datetime for Waterloo Place: 2026-08-25 10:00:00
Max datetime for Waterloo Place: None
Max datetime for London Westminster: 2026-08-25 10:00:00
Max datetime for Camden Kerbside: 2026-08-25 10:00:00
Max datetime for Tower Hamlets: 2026-08-25 10:00:00
Max datetime for Tower Hamlets: None
Max datetime for Greenwich: 2026-08-25 10:00:00
Max datetime for Greenwich: None
Max datetime for London Honor Oak Park: 2026-08-25 10:00:00
Max datetime for Brent: None
Max datetime for Brent: 2026-08-25 10:00:00
Processing Waterloo Place: sensor 1561901

Processing Waterloo Place: sensor 16318059

Processing London Westminster: sensor 28890

Processing Camden Kerbside: sensor 235

Processing Tower Hamlets: sensor 2009625

Processing Tower Hamlets: sensor 16318037

Processing Greenwich: sensor 1304607

Processing Greenwich: sensor 16317995

Processing London Honor Oak Park: sensor 1304734

<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - London Westminster: sensor 28890)
Processed 0 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Tower Hamlets: sensor 16318037)
Processed 0 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Greenwich: sensor 16317995)
Processed 0 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Waterloo Place: sensor 16318059)
Processed 0 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Camden Kerbside: sensor 235)
Processed 0 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Greenwich: sensor 1304607)
Processed 50 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Waterloo Place: sensor 1561901)
Processed 109 records
Finished processing all records - London Westminster: sensor 28890
Processing Brent: sensor 16317960

<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Tower Hamlets: sensor 2009625)
Processed 83 records
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - London Honor Oak Park: sensor 1304734)
Processed 109 records
Finished processing all records - Tower Hamlets: sensor 16318037
Processing Brent: sensor 6955371

<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Brent: sensor 16317960)
Processed 0 records
Finished processing all records - Greenwich: sensor 16317995
Finished processing all records - Waterloo Place: sensor 16318059
Finished processing all records - Camden Kerbside: sensor 235
<Response [200]> -- processing page 1 (end date 2026-08-30T11:00:00 - Brent: sensor 6955371)
Processed 70 records
Finished processing all records - Greenwich: sensor 1304607
Finished processing all records - Waterloo Place: sensor 1561901
Finished processing all records - Tower Hamlets: sensor 2009625
Finished processing all records - London Honor Oak Park: sensor 1304734
Finished processing all records - Brent: sensor 16317960
Finished processing all records - Brent: sensor 6955371

Processing London Westminster - long -0.0180219908165375 & lat 51.5029878731458, status code: 429
Processing Greenwich - long -0.0180219908165375 & lat 51.5029878731458, status code: 200

Processing Waterloo Place - long -0.0180219908165375 & lat 51.5029878731458, status code: 200

Fail on London Westminster due to 429 Client Error: Too Many Requests for url: https://archive-api.open-meteo.com/v1/archive?latitude=51.5029878731458&longitude=-0.0180219908165375&start_date=2026-08-25&end_date=2026-08-30&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,rain&timezone=auto
RETRYING...

Processing Tower Hamlets - long -0.0180219908165375 & lat 51.5029878731458, status code: 200

Processing Camden Kerbside - long -0.0180219908165375 & lat 51.5029878731458, status code: 200
Finished on Greenwich

Processing London Honor Oak Park - long -0.0180219908165375 & lat 51.5029878731458, status code: 200
Finished on Camden Kerbside
Finished on Tower Hamlets
Finished on London Honor Oak Park
Finished on Waterloo Place

Processing Brent - long -0.0180219908165375 & lat 51.5029878731458, status code: 200
Finished on Brent

Processing London Westminster - long -0.0180219908165375 & lat 51.5029878731458, status code: 200
Finished on London Westminster
Condition before cleaning:
On merged dataset found 0 duplicated records, missing value details:
time                      0
temperature_2m            0
relative_humidity_2m      0
wind_speed_10m            0
surface_pressure          0
rain                      0
station_id_london         0
station_name              0
long                      0
lat                       0
location_id             587
location_name           587
sensor_id               587
values_pm25             587
timestamp_from          587
timestamp_to            587
dtype: int64
Stations with > 1 sensors sending values? False
Stations with 0 sensors sending values? True
Stations with inconsistent names? 0

Condition after cleaning:
On merged dataset found 0 duplicated records, missing value details:
time                      0
temperature_2m            0
relative_humidity_2m      0
wind_speed_10m            0
surface_pressure          0
rain                      0
station_id_london         0
station_name              0
long                      0
lat                       0
location_id               0
location_name             0
sensor_id                 0
values_pm25             299
timestamp_from            0
weather_id                0
dtype: int64
Stations with > 1 sensors sending values? False
Stations with 0 sensors sending values? False
Stations with inconsistent names? 0

In [11]:
serve_whole_data(username_postgres, pw_postgres, db_name, limit=10000)

Existence of DB data_warehouse_weather: True

c:\Users\user\works\DE_studies\pm25_forecast\functions\database_actions_functions.py:164: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  table_result = pd.io.sql.read_sql_query(f'''

Saved cleaned, read-ML data to c:\Users\user\works\DE_studies\pm25_forecast\datasets_aggr\weather_readings_mlready.csv

,weather_id,sensor_id,station_id,station_name,time_reading,temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,rain,pm25,longitude,latitude
0,W1561901_2023010100,1561901,270693,Waterloo Place,2023-01-01 00:00:00,12.1,89.0,34.1,999.1,0.3,5.1,-0.133068,51.507582
1,W1561901_2023010101,1561901,270693,Waterloo Place,2023-01-01 01:00:00,11.3,94.0,22.9,999.1,0.1,6.2,-0.133068,51.507582
2,W1561901_2023010102,1561901,270693,Waterloo Place,2023-01-01 02:00:00,11.9,85.0,31.1,999.9,0.4,6.6,-0.133068,51.507582
3,W1561901_2023010103,1561901,270693,Waterloo Place,2023-01-01 03:00:00,11.0,80.0,31.4,1000.9,0.0,7.9,-0.133068,51.507582
4,W1561901_2023010104,1561901,270693,Waterloo Place,2023-01-01 04:00:00,10.4,78.0,30.7,1001.9,0.0,8.3,-0.133068,51.507582
...,...,...,...,...,...,...,...,...,...,...,...,...,...
224687,W1304607_2026083009,1304607,225751,Greenwich,2026-08-30 09:00:00,17.8,81.0,13.4,1005.8,0.0,NaN,0.095111,51.486957
224688,W1304607_2026083010,1304607,225751,Greenwich,2026-08-30 10:00:00,18.7,75.0,12.7,1006.1,0.0,NaN,0.095111,51.486957
224689,W6955371_2026082512,6955371,225719,Brent,2026-08-25 12:00:00,23.6,40.0,17.4,1008.8,0.0,5.0,-0.247793,51.537799
224690,W6955371_2026083009,6955371,225719,Brent,2026-08-30 09:00:00,17.8,81.0,13.4,1005.8,0.0,NaN,-0.247793,51.537799
224691,W6955371_2026083010,6955371,225719,Brent,2026-08-30 10:00:00,18.7,75.0,12.7,1006.1,0.0,NaN,-0.247793,51.537799