# **Importing Libraries**
---
---

In [1]:
# Concurrent processing & automation
import threading

# for file manipulation & environment variable
import os
from dotenv import load_dotenv

# importing functions
from functions.ingestion_functions import get_pm25_reads, get_weather_readings

# **Initialization & Environment Variable Extraction**
---
---

In [2]:
load_dotenv() # load environment variables
thread_local = threading.local() # Initializing thread local storage

headers = {
    'X-API-Key': os.getenv('API_OPENAQ') # initializing request header
}

# Initialization of datasets directory for raw csv datasets
path_datasets_raw = os.path.join(os.getcwd(), 'datasets_raw')
if not os.path.exists(path_datasets_raw):
    os.makedirs(path_datasets_raw)

# List of specific stations & their OpenAQ ids
list_needed_stations = {
    'Waterloo Place': 270693,
    'London Westminster': 159,
    'Camden Kerbside': 152,
    'Tower Hamlets': 290183,
    'Greenwich': 225751,
    'London Honor Oak Park': 225803
}
start = '2023-01-01' # start date for weather data
end = '2026-07-29' # end date for weather data

# **Extracting PM 2.5 Readings in London**
---
---

In [3]:
'''from extraction_functions import get_station_details

station_details = get_station_details(list_needed_stations)
#df_station_details = convert_station_details_csv(station_details)
display(station_details)'''

'from extraction_functions import get_station_details\n\nstation_details = get_station_details(list_needed_stations)\n#df_station_details = convert_station_details_csv(station_details)\ndisplay(station_details)'

In [4]:
df_pm25_readings = get_pm25_reads(list_needed_stations, start, end, header=headers, folder_name='datasets_raw')

Getting sensors in London Honor Oak Park
Getting sensors in London Westminster
Getting sensors in Tower Hamlets
Getting sensors in Camden Kerbside
Getting sensors in Waterloo Place
Getting sensors in Greenwich
Saved station details to: c:\Users\user\works\DE_studies\openmeteo_ml\datasets_raw\station_sensors.csv


Processing Waterloo Place: sensor 1561901

Processing Waterloo Place: sensor 16318059

Processing London Westminster: sensor 28890

Processing Camden Kerbside: sensor 235

Processing Tower Hamlets: sensor 2009625

Processing Tower Hamlets: sensor 16318037

Processing Greenwich: sensor 1304607

Processing Greenwich: sensor 16317995

Processing London Honor Oak Park: sensor 1304734

<Response [200]> -- processing page 1 (end date 2024-01-01 - Greenwich: sensor 16317995)<Response [200]> -- processing page 1 (end date 2024-01-01 - Tower Hamlets: sensor 16318037)
Processed 0 records

Processed 0 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - Waterloo Place: sensor 16318059)
Processed 0 records
Finished processing all records - Greenwich: sensor 16317995Finished processing all records - Tower Hamlets: sensor 16318037

Finished processing all records - Waterloo Place: sensor 16318059
<Response [200]> -- processing page 1 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 1000 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 1000 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 1000 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - Tower Hamlets: sensor 2009625)
Processed 997 records
<Response [200]> -- processing page 2 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 2000 records
<Response [200]> -- processing page 2 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 2000 records
Finished processing all records - Tower Hamlets: sensor 2009625
<Response [200]> -- processing page 2 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 2000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 3000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 3000 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 1000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 3000 records
<Response [200]> -- processing page 4 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 4000 records
<Response [200]> -- processing page 4 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 4000 records
<Response [200]> -- processing page 1 (end date 2024-01-01 - Greenwich: sensor 1304607)
Processed 1000 records
<Response [200]> -- processing page 2 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 2000 records
<Response [200]> -- processing page 4 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 4000 records
<Response [200]> -- processing page 5 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 5000 records
<Response [200]> -- processing page 2 (end date 2024-01-01 - Greenwich: sensor 1304607)
Processed 2000 records
<Response [200]> -- processing page 5 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 5000 records
<Response [200]> -- processing page 5 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 5000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 3000 records
<Response [200]> -- processing page 3 (end date 2024-01-01 - Greenwich: sensor 1304607)
Processed 3000 records
<Response [200]> -- processing page 6 (end date 2024-01-01 - Waterloo Place: sensor 1561901)
Processed 5786 records
<Response [200]> -- processing page 6 (end date 2024-01-01 - Camden Kerbside: sensor 235)
Processed 5649 records
<Response [200]> -- processing page 4 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 4000 records
Finished processing all records - Waterloo Place: sensor 1561901
<Response [200]> -- processing page 6 (end date 2024-01-01 - London Westminster: sensor 28890)
Processed 5589 records
Finished processing all records - Camden Kerbside: sensor 235
Finished processing all records - London Westminster: sensor 28890
<Response [200]> -- processing page 4 (end date 2024-01-01 - Greenwich: sensor 1304607)
Processed 3716 records
Finished processing all records - Greenwich: sensor 1304607
<Response [200]> -- processing page 5 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 5000 records
<Response [200]> -- processing page 6 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 6000 records
<Response [200]> -- processing page 7 (end date 2024-01-01 - London Honor Oak Park: sensor 1304734)
Processed 6950 records
Finished processing all records - London Honor Oak Park: sensor 1304734

<Response [200]> -- processing page 1 (end date 2025-01-01 - Tower Hamlets: sensor 2009625)
Processed 1997 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - Tower Hamlets: sensor 2009625)
Processed 2997 records
<Response [200]> -- processing page 3 (end date 2025-01-01 - Tower Hamlets: sensor 2009625)
Processed 3462 records
Finished processing all records - Tower Hamlets: sensor 2009625




<Response [200]> -- processing page 1 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 6649 records
<Response [200]> -- processing page 1 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 6786 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 7649 records
<Response [200]> -- processing page 1 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 6589 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 7786 records
<Response [200]> -- processing page 1 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 4716 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 7589 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 5716 records

<Response [200]> -- processing page 3 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 8786 records
<Response [200]> -- processing page 3 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 8589 records
<Response [200]> -- processing page 3 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 6716 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 9589 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 9786 records
<Response [200]> -- processing page 1 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 7950 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 7716 records
<Response [200]> -- processing page 2 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 8950 records
<Response [200]> -- processing page 5 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 10589 records
<Response [200]> -- processing page 5 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 10786 records
<Response [500]> -- processing page 3 (end date 2025-01-01 - Camden Kerbside: sensor 235)
<Response [200]> -- processing page 5 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 8716 records
<Response [200]> -- processing page 6 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 11589 records
<Response [200]> -- processing page 6 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 11786 records
<Response [200]> -- processing page 3 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 9950 records
<Response [200]> -- processing page 6 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 9716 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 10950 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 12589 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 12786 records
<Response [200]> -- processing page 8 (end date 2025-01-01 - London Westminster: sensor 28890)
Processed 12694 records
<Response [200]> -- processing page 5 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 11950 records
Finished processing all records - London Westminster: sensor 28890
<Response [200]> -- processing page 8 (end date 2025-01-01 - Waterloo Place: sensor 1561901)
Processed 12863 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 10716 records
Finished processing all records - Waterloo Place: sensor 1561901
<Response [200]> -- processing page 6 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 12950 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 13950 records
<Response [200]> -- processing page 8 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 11716 records
<Response [200]> -- processing page 8 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 14950 records
<Response [200]> -- processing page 9 (end date 2025-01-01 - Greenwich: sensor 1304607)
Processed 12304 records
Finished processing all records - Greenwich: sensor 1304607
<Response [200]> -- processing page 9 (end date 2025-01-01 - London Honor Oak Park: sensor 1304734)
Processed 15610 records
Finished processing all records - London Honor Oak Park: sensor 1304734

<Response [200]> -- processing page 1 (end date 2026-01-01 - Tower Hamlets: sensor 2009625)
Processed 4462 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - Tower Hamlets: sensor 2009625)
Processed 5462 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - Tower Hamlets: sensor 2009625)
Processed 6462 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - Tower Hamlets: sensor 2009625)
Processed 6639 records
Finished processing all records - Tower Hamlets: sensor 2009625
<Response [200]> -- processing page 3 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 8649 records
<Response [200]> -- processing page 4 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 9649 records
<Response [200]> -- processing page 5 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 10649 records


<Response [200]> -- processing page 1 (end date 2026-01-01 - London Westminster: sensor 28890)
Processed 13694 records
<Response [200]> -- processing page 6 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 11649 records
<Response [200]> -- processing page 1 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 13863 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - London Westminster: sensor 28890)
Processed 14694 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 14863 records
<Response [200]> -- processing page 7 (end date 2025-01-01 - Camden Kerbside: sensor 235)
Processed 11745 records
Finished processing all records - Camden Kerbside: sensor 235
<Response [200]> -- processing page 3 (end date 2026-01-01 - London Westminster: sensor 28890)
Processed 15694 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 15863 records

<Response [200]> -- processing page 4 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 16863 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - London Westminster: sensor 28890)
Processed 16694 records

<Response [200]> -- processing page 5 (end date 2026-01-01 - London Westminster: sensor 28890)
Processed 17154 records
<Response [200]> -- processing page 5 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 17863 records
<Response [200]> -- processing page 1 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 13304 records
Finished processing all records - London Westminster: sensor 28890
<Response [200]> -- processing page 1 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 16610 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 14304 records
<Response [200]> -- processing page 6 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 18863 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 17610 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 15304 records
<Response [200]> -- processing page 7 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 19863 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 18610 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 16304 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 19610 records
<Response [200]> -- processing page 8 (end date 2026-01-01 - Waterloo Place: sensor 1561901)
Processed 20859 records
Finished processing all records - Waterloo Place: sensor 1561901
<Response [200]> -- processing page 5 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 20610 records
<Response [200]> -- processing page 5 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 17304 records
<Response [200]> -- processing page 1 (end date 2026-07-29 - Tower Hamlets: sensor 2009625)
Processed 7639 records
<Response [200]> -- processing page 6 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 21610 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - Tower Hamlets: sensor 2009625)
Processed 8639 records
<Response [200]> -- processing page 6 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 18304 records
<Response [200]> -- processing page 3 (end date 2026-07-29 - Tower Hamlets: sensor 2009625)
Processed 9639 records
<Response [200]> -- processing page 7 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 22610 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - Tower Hamlets: sensor 2009625)
Processed 10639 records
<Response [200]> -- processing page 7 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 19304 records
<Response [200]> -- processing page 8 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 23610 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - Tower Hamlets: sensor 2009625)
Processed 11123 records
Finished processing all records - Tower Hamlets: sensor 2009625
<Response [200]> -- processing page 9 (end date 2026-01-01 - London Honor Oak Park: sensor 1304734)
Processed 24264 records
Finished processing all records - London Honor Oak Park: sensor 1304734
<Response [200]> -- processing page 8 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 20304 records
<Response [200]> -- processing page 9 (end date 2026-01-01 - Greenwich: sensor 1304607)
Processed 20964 records
Finished processing all records - Greenwich: sensor 1304607

<Response [200]> -- processing page 1 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 12745 records
<Response [200]> -- processing page 2 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 13745 records
<Response [200]> -- processing page 3 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 14745 records
<Response [200]> -- processing page 1 (end date 2026-07-29 - London Westminster: sensor 28890)
Processed 18154 records
<Response [200]> -- processing page 4 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 15745 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - London Westminster: sensor 28890)
Processed 19154 records
<Response [200]> -- processing page 5 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 16745 records
<Response [200]> -- processing page 3 (end date 2026-07-29 - London Westminster: sensor 28890)
Processed 20154 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - London Westminster: sensor 28890)
Processed 21154 records
<Response [200]> -- processing page 6 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 17745 records
<Response [200]> -- processing page 1 (end date 2026-07-29 - Waterloo Place: sensor 1561901)
Processed 21859 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - London Westminster: sensor 28890)
Processed 21629 records
Finished processing all records - London Westminster: sensor 28890
<Response [200]> -- processing page 2 (end date 2026-07-29 - Waterloo Place: sensor 1561901)
Processed 22859 records
<Response [200]> -- processing page 7 (end date 2026-01-01 - Camden Kerbside: sensor 235)
Processed 18413 records
Finished processing all records - Camden Kerbside: sensor 235
<Response [200]> -- processing page 3 (end date 2026-07-29 - Waterloo Place: sensor 1561901)
Processed 23859 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - Waterloo Place: sensor 1561901)
Processed 24859 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - Waterloo Place: sensor 1561901)
Processed 25696 records
Finished processing all records - Waterloo Place: sensor 1561901
<Response [200]> -- processing page 1 (end date 2026-07-29 - London Honor Oak Park: sensor 1304734)
Processed 25264 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - London Honor Oak Park: sensor 1304734)
Processed 26264 records
<Response [200]> -- processing page 3 (end date 2026-07-29 - London Honor Oak Park: sensor 1304734)
Processed 27264 records
<Response [200]> -- processing page 1 (end date 2026-07-29 - Greenwich: sensor 1304607)
Processed 21964 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - London Honor Oak Park: sensor 1304734)
Processed 28264 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - Greenwich: sensor 1304607)
Processed 22964 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - London Honor Oak Park: sensor 1304734)
Processed 29244 records
Finished processing all records - London Honor Oak Park: sensor 1304734
<Response [200]> -- processing page 3 (end date 2026-07-29 - Greenwich: sensor 1304607)
Processed 23964 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - Greenwich: sensor 1304607)
Processed 24964 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - Greenwich: sensor 1304607)
Processed 25784 records
Finished processing all records - Greenwich: sensor 1304607
<Response [200]> -- processing page 1 (end date 2026-07-29 - Camden Kerbside: sensor 235)
Processed 19413 records
<Response [200]> -- processing page 2 (end date 2026-07-29 - Camden Kerbside: sensor 235)
Processed 20413 records
<Response [200]> -- processing page 3 (end date 2026-07-29 - Camden Kerbside: sensor 235)
Processed 21413 records
<Response [200]> -- processing page 4 (end date 2026-07-29 - Camden Kerbside: sensor 235)
Processed 22413 records
<Response [200]> -- processing page 5 (end date 2026-07-29 - Camden Kerbside: sensor 235)
Processed 22983 records
Finished processing all records - Camden Kerbside: sensor 235


In [5]:
df_pm25_readings

,location_id,location_name,sensor_id,values_pm25,timestamp_from,timestamp_to
0,290183.0,Tower Hamlets,2009625.0,6.4,2023-01-02T23:00:00Z,2023-01-03T00:00:00Z
1,290183.0,Tower Hamlets,2009625.0,6.4,2023-01-03T00:00:00Z,2023-01-03T01:00:00Z
2,290183.0,Tower Hamlets,2009625.0,5.4,2023-01-03T01:00:00Z,2023-01-03T02:00:00Z
3,290183.0,Tower Hamlets,2009625.0,5.6,2023-01-03T02:00:00Z,2023-01-03T03:00:00Z
4,290183.0,Tower Hamlets,2009625.0,5.7,2023-01-03T03:00:00Z,2023-01-03T04:00:00Z
...,...,...,...,...,...,...
136454,152.0,Camden Kerbside,235.0,9.0,2026-07-27T18:00:00Z,2026-07-27T19:00:00Z
136455,152.0,Camden Kerbside,235.0,8.0,2026-07-27T19:00:00Z,2026-07-27T20:00:00Z
136456,152.0,Camden Kerbside,235.0,11.0,2026-07-27T20:00:00Z,2026-07-27T21:00:00Z
136457,152.0,Camden Kerbside,235.0,13.0,2026-07-27T21:00:00Z,2026-07-27T22:00:00Z
136458,152.0,Camden Kerbside,235.0,10.0,2026-07-27T22:00:00Z,2026-07-27T23:00:00Z

# **Extracting Weather Readings in London**
---
---

In [6]:
df_weathers = get_weather_readings(start, end, list_needed_stations, folder_name='datasets_raw')

Getting sensors in London Westminster
Getting sensors in London Honor Oak Park
Getting sensors in Waterloo Place
Getting sensors in Greenwich
Getting sensors in Camden Kerbside
Getting sensors in Tower Hamlets

Processing Waterloo Place - long -0.133068372704093 & lat 51.5075819137762, status code: 429
Fail on Waterloo Place due to 429 Client Error: Too Many Requests for url: https://archive-api.open-meteo.com/v1/archive?latitude=51.5075819137762&longitude=-0.133068372704093&start_date=2023-01-01&end_date=2026-07-29&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,rain&timezone=auto
RETRYING...

Processing Greenwich - long 0.095111 & lat 51.486957, status code: 200
Finished on Greenwich

Processing London Honor Oak Park - long -0.0374153592115306 & lat 51.4496728960354, status code: 200
Finished on London Honor Oak Park

Processing Tower Hamlets - long -0.0180219908165375 & lat 51.5029878731458, status code: 200

Processing London Westminster - long -0.13193099964204494 & lat 51.4946699996591, status code: 200
Finished on Tower Hamlets
Finished on London Westminster

Processing Camden Kerbside - long -0.17526899971392015 & lat 51.54420999974351, status code: 200
Finished on Camden Kerbside

Processing Waterloo Place - long -0.133068372704093 & lat 51.5075819137762, status code: 200
Finished on Waterloo Place

In [7]:
df_weathers

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,surface_pressure,rain,station_id_london,station_name,long,lat
0,2023-01-01T00:00,12.1,89,34.1,999.1,0.3,270693,Waterloo Place,-0.133068,51.507582
1,2023-01-01T01:00,11.3,94,22.9,999.1,0.1,270693,Waterloo Place,-0.133068,51.507582
2,2023-01-01T02:00,11.9,85,31.1,999.9,0.4,270693,Waterloo Place,-0.133068,51.507582
3,2023-01-01T03:00,11.0,80,31.4,1000.9,0.0,270693,Waterloo Place,-0.133068,51.507582
4,2023-01-01T04:00,10.4,78,30.7,1001.9,0.0,270693,Waterloo Place,-0.133068,51.507582
...,...,...,...,...,...,...,...,...,...,...
188059,2026-07-29T19:00,30.0,33,16.8,1008.5,0.0,225803,London Honor Oak Park,-0.037415,51.449673
188060,2026-07-29T20:00,28.3,36,15.9,1008.7,0.0,225803,London Honor Oak Park,-0.037415,51.449673
188061,2026-07-29T21:00,26.2,41,15.0,1009.1,0.0,225803,London Honor Oak Park,-0.037415,51.449673
188062,2026-07-29T22:00,25.1,45,12.5,1009.8,0.0,225803,London Honor Oak Park,-0.037415,51.449673
188063,2026-07-29T23:00,24.8,49,9.9,1010.0,0.0,225803,London Honor Oak Park,-0.037415,51.449673